/*
 * InfoDialog.java
 *
 * Created on 13. Februar 2005, 10:53
 */

package de.gidoo.owl;

import javax.swing.event.*;
import java.util.*;
/**
 * Displays infos about the program, the licence and the link to the homepage.
 * @author Thomas Krause
 */
public class InfoDialog extends javax.swing.JDialog {
  
    private ResourceBundle i18n;
  
    /** Creates new form InfoDialog */
    public InfoDialog(java.awt.Frame parent, boolean modal, ResourceBundle i18n) {
        super(parent, modal);
        
        this.i18n = i18n;
        initComponents();
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    btOk = new javax.swing.JButton();
    tabPanel = new javax.swing.JTabbedPane();
    panGeneral = new javax.swing.JPanel();
    lblTitle = new javax.swing.JLabel();
    lblText = new javax.swing.JLabel();
    lblIcon = new javax.swing.JLabel();
    panLicence = new javax.swing.JPanel();
    scrollLicence = new javax.swing.JScrollPane();
    lblLicence = new javax.swing.JEditorPane();
    jPanel1 = new javax.swing.JPanel();
    lblHelp = new javax.swing.JLabel();

    getContentPane().setLayout(null);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(java.util.ResourceBundle.getBundle("de/gidoo/owl/OwlReader").getString("infoTitle"));
    setFont(new java.awt.Font("Dialog", 0, 12));
    setResizable(false);
    btOk.setFont(new java.awt.Font("Dialog", 0, 12));
    btOk.setMnemonic(i18n.getString("btCloseChar").charAt(0));
    btOk.setText(i18n.getString("btClose"));
    btOk.setName("btOk");
    btOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okClicked(evt);
      }
    });

    getContentPane().add(btOk);
    btOk.setBounds(0, 320, 390, 25);

    tabPanel.setFont(new java.awt.Font("Dialog", 0, 12));
    panGeneral.setLayout(null);

    lblTitle.setFont(new java.awt.Font("Dialog", 1, 18));
    lblTitle.setForeground(new java.awt.Color(0, 0, 153));
    lblTitle.setText(i18n.getString("infoTitleGeneral"));
    panGeneral.add(lblTitle);
    lblTitle.setBounds(70, 20, 120, 30);

    lblText.setFont(new java.awt.Font("Dialog", 0, 12));
    lblText.setText(i18n.getString("infoTextGeneral"));
    lblText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    panGeneral.add(lblText);
    lblText.setBounds(10, 70, 370, 210);

    lblIcon.setIcon(new javax.swing.ImageIcon("res/icon48.png"));
    panGeneral.add(lblIcon);
    lblIcon.setBounds(10, 10, 48, 48);

    tabPanel.addTab(i18n.getString("infoTabGeneral"), panGeneral);

    panLicence.setLayout(new java.awt.GridLayout(1, 0));

    panLicence.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        licenceReset(evt);
      }
    });

    scrollLicence.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    lblLicence.setContentType("text/html");
    lblLicence.setEditable(false);
    lblLicence.setText(i18n.getString("infoLicenceText"));
    lblLicence.setContentType("text/html");
    lblLicence.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
      public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
        hyperLinkUpdate(evt);
      }
    });

    scrollLicence.setViewportView(lblLicence);

    panLicence.add(scrollLicence);

    tabPanel.addTab(i18n.getString("infoTabLicence"), panLicence);

    jPanel1.setLayout(new java.awt.GridLayout(1, 1));

    lblHelp.setFont(new java.awt.Font("Dialog", 0, 12));
    lblHelp.setText(i18n.getString("infoHelp"));
    jPanel1.add(lblHelp);

    tabPanel.addTab(i18n.getString("infoTabHelp"), jPanel1);

    getContentPane().add(tabPanel);
    tabPanel.setBounds(0, 0, 390, 310);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-401)/2, (screenSize.height-381)/2, 401, 381);
  }
  // </editor-fold>//GEN-END:initComponents

    /**
     * Shows the full text of an abbrivation if mouse is over it.
     */
    private void hyperLinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_hyperLinkUpdate
        
        String address = "";
        String title = "";
        java.awt.Graphics gc;
        java.awt.Point mousePos;
        
        // look what kind of action
        
        HyperlinkEvent.EventType type = evt.getEventType();
        if(type == HyperlinkEvent.EventType.ENTERED)
        {
          // just ENTERED
          address = evt.getDescription();
                   
          if(address.startsWith("?abbr:"))
          {
            title = address.substring(6);
              
            gc = getGraphics();
            mousePos = getMousePosition();
            
            update(gc);
            java.awt.Color oldColor = gc.getColor();
            java.awt.Color newColor = new java.awt.Color(255, 200, 0);
            
            // inner rectangle
            gc.setColor(newColor);
            java.awt.FontMetrics fm = gc.getFontMetrics();
            
            int rectX = mousePos.x;
            int rectY = mousePos.y - fm.getHeight() + fm.getDescent();
            int rectHeight = fm.getHeight();
            int rectWidth = fm.stringWidth(title);
            
            gc.fillRect(rectX, rectY, rectWidth, rectHeight);
            
            // bounds
            newColor = new java.awt.Color(0, 0, 0);
            gc.setColor(newColor);
            gc.drawRect(rectX - 1, rectY - 1, rectWidth + 1, rectHeight + 1);
            
            // text
            newColor = new java.awt.Color(0, 0, 0);
            gc.setColor(newColor);            
            gc.drawString(title, mousePos.x, mousePos.y);
            gc.setColor(oldColor);
            
          }
        }
        else if(type == HyperlinkEvent.EventType.EXITED)
        {
          // just EXITED
          address = evt.getDescription();
          if(address.startsWith("?abbr:"))
          {
             gc = getGraphics();
             update(gc);
          }
        }
        
    }//GEN-LAST:event_hyperLinkUpdate
    
    /**
     * Scroll to the begin of the licence.
     */
    private void licenceReset(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_licenceReset
        lblLicence.scrollToReference("start");
        
    }//GEN-LAST:event_licenceReset

    /**
     * User requested to close the window by clicking on "ok".
     */
    private void okClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okClicked
      this.setVisible(false);
    }//GEN-LAST:event_okClicked
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btOk;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblHelp;
  private javax.swing.JLabel lblIcon;
  private javax.swing.JEditorPane lblLicence;
  private javax.swing.JLabel lblText;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JPanel panGeneral;
  private javax.swing.JPanel panLicence;
  private javax.swing.JScrollPane scrollLicence;
  private javax.swing.JTabbedPane tabPanel;
  // End of variables declaration//GEN-END:variables
    
}
