/*
 * BaseSuite.java
 * JUnit based test
 *
 * Created on 6. August 2006, 19:06
 */

package de.gidoo.owl2.base;

import junit.framework.*;

/**
 *
 * @author thomas
 */
public class BaseSuite extends TestCase {
  
  public BaseSuite(String testName) {
    super(testName);
  }

  protected void setUp() throws Exception {
  }

  protected void tearDown() throws Exception {
  }

  /**
   * suite method automatically generated by JUnit module
   */
  public static Test suite() {
    TestSuite suite = new TestSuite("BaseSuite");
    suite.addTest(de.gidoo.owl2.base.SQLiteProviderTest.suite());
    return suite;
  }
  
}
